#!/bin/sh
# /etc/init.d/autowakeup
#
# AUTHOR:	BoldarBlood - K. Walde 21/03/2012
# Correctly starts / stops / restarts Solo0815s Autowakeup script at system startup
 # changed by Solo0815 - 2013-09-20
# - added status
# - added functions
# - removed set -e (from /etc/init.d/skeleton)

### BEGIN INIT INFO
# Provides:          autowakeup
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     0 1 2 3 4 5 6
# Default-Stop:
# Short-Description: runs autowakeup at boot and shutdown
# Description:       autowakeup
### END INIT INFO

# Some things that run always

# Do NOT "set -e" -> from /etc/init.d/skeleton
#set -e

# Must be a valid filename
NAME=autowakeup
#This is the command to be run, give the full pathname
DAEMON=/usr/local/bin/autowakeup.sh
DAEMON_OPTS=""

# read LSB init-functions
. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0


case "$1" in
	start)
		start-stop-daemon --start --quiet --background --exec $DAEMON || return 1
		if [ $? -ne 0 ]; then
			logger -t /etc/init.d/autowakeup "$NAME starting failed!"
			echo -n "$NAME starting" && log_end_msg 1
		else
			logger -t /etc/init.d/autowakeup "$NAME started successful!"
			echo -n "$NAME starting" && log_end_msg 0
		fi
		echo "."
		;;
	status)
		#rtcwake -l -m show
		$DAEMON show
		;;
	*)
		echo "Usage: "$1" {start|status}"
		exit 1
		;;
esac

exit 0